#!/bin/sh
#
# `hl` : Highlight matching strings

die ()
{
	echo "hl: $*" >&2
	exit 1
}

main ()
{
	case "$1" in
		-k) shift; color=30 ;;
		-K) shift; color='1;30' ;;
		-r) shift; color=31 ;;
		-R) shift; color='1;31' ;;
		-g) shift; color=32 ;;
		-G) shift; color='1;32' ;;
		-y) shift; color=33 ;;
		-Y) shift; color='1;33' ;;
		-b) shift; color=34 ;;
		-B) shift; color='1;34' ;;
		-m) shift; color=35 ;;
		-M) shift; color='1;35' ;;
		-c) shift; color=36 ;;
		-C) shift; color='1;36' ;;
		-w) shift; color=37 ;;
		-W) shift; color='1;37' ;;
		--python) shift; syntax='python' ;;
		-*) die "unknown option: $1"
	esac

	color=$(printf '%b' "\033[${color:-1;31}m")
	clear=$(printf '\033[m')

	if test -f "$1"; then
		exec <"$1"
		regex='.*'
	elif test -f "$2"; then
		exec <"$2"
		regex="$1"
	fi

	case "$syntax" in
		python)
			sed -e 's/^\([[:space:]]*def \)\([^(]*\)/\1[1;32m\2[m/' \
			    -e '/^[^#]*$/s/['\''"][^'\''"]*['\''"]/[36m&[m/' \
			    -e 's/\([^\]\)\(#.*\)/\1[1;34m\2[m/'
			;;
		*)
			sed "s/${regex}/${color}&${clear}/"
	esac

}

main "$@"
