#!/bin/sh
#
# `hl` : Highlight matching strings

die ()
{
	echo "hl: $*" >&2
	exit 1
}

main ()
{
	case $1 in
	-k) shift ; color=30 ;;
	-K) shift ; color='1;30' ;;
	-r) shift ; color=31 ;;
	-R) shift ; color='1;31' ;;
	-g) shift ; color=32 ;;
	-G) shift ; color='1;32' ;;
	-y) shift ; color=33 ;;
	-Y) shift ; color='1;33' ;;
	-b) shift ; color=34 ;;
	-B) shift ; color='1;34' ;;
	-m) shift ; color=35 ;;
	-M) shift ; color='1;35' ;;
	-c) shift ; color=36 ;;
	-C) shift ; color='1;36' ;;
	-w) shift ; color=37 ;;
	-W) shift ; color='1;37' ;;
	-*) die "unknown option: $1"
	esac
	regex="${1:-.*}"
	test -f "$2" && exec <"$2"
	awk "{gsub(\"${regex}\", \"\033[${color:-1;31}m&\033[m\"); print}"
}

main "$@"
