#!/bin/sh
#
# `hl` : Highlight matching strings


k='30'
K='1;30'
r='31'
R='1;31'
g='32'
G='1;32'
y='33'
Y='1;33'
b='34'
B='1;34'
m='35'
M='1;35'
c='36'
C='1;36'
w='37'
W='1;37'
clear=$(printf '\033[m')


die() {
    echo "hl: $*" >&2
    exit 1
}


main() {
    while test $# -gt 0; do
        case "$1" in
            -[kKrRgGyYbBmMcCwW])
                eval "color=\${${1#-}}"
                color=$(printf '%b' "\033[${color}m")
                shift
                ;;
            --python)
                shift
                syntax='python'
                ;;
            --)
                shift
                break
                ;;
            -*)
                die "unknown option: $1"
                ;;
            *)
                if ! test -f "$1"; then
                    regex="$1"
                    shift
                fi
                break
        esac
    done

    # The first file read defines the syntax for all files.
    case "$1" in
        *.py)
            syntax='python'
    esac

    case "$syntax" in
        python)
            sed -e 's/^\([[:space:]]*def \)\([^(]*\)/\1[1;32m\2[m/g' \
                -e 's/^\([[:space:]]*class \)\([^(]*\)/\1[1;31m\2[m/g' \
                -e '/^[^#]*$/s/['\''"][^'\''"]*['\''"]/[36m&[m/g' \
                -e 's/\([^\]\)\(#.*\)/\1[1;34m\2[m/g' \
                "$@"
            ;;
        *)
            sed "s/${regex:-.*}/${color}&${clear}/" "$@"
    esac
}


main "$@"
