#!/bin/sh
#
# `posix` : Check the POSIX 2028 specification from the command line

main ()
{
	if test -z "$BROWSER"
	then
		command -v lynx && BROWSER=lynx
		command -v w3m && BROWSER=w3m  # w3m preferred
	fi >/dev/null 2>&1

	case $1 in
	-i)
		interactive=1
		shift
	esac

	url="https://pubs.opengroup.org/onlinepubs/9699919799/utilities/${*}.html"

	if test "$interactive" -eq 1
	then
		exec "$BROWSER" "$url"
	else
		prompt="POSIX manual page\: ${*} (Page %db/%D)"
		exec "$BROWSER" -dump "$url" | less -P "$prompt"
	fi
}

main "$@"
